/**
 * Seeded Manufacturing Knowledge catalog — structured entities only.
 * Freeze-safe: in-memory domain catalog, no new persistence ports.
 */
import type {
  BusinessRuleDefinition,
  DecisionDefinition,
  DictionaryEntry,
  FormulaDefinition,
  KnowledgeConceptEdge,
  KnowledgeConceptNode,
  KpiDefinition,
  MachineDefinition,
  OperationDefinition,
  ProductionFlowDefinition,
  ReasoningSchema,
} from './types'

export const KNOWLEDGE_CONCEPTS: KnowledgeConceptNode[] = [
  { id: 'c-cotton', label: 'Cotton Fabric', category: 'TextileTerminology', definition: 'Natural fiber woven/knitted fabric used as primary garment material.', moduleRefs: ['product-card', 'inventory'], tags: ['fabric', 'material'] },
  { id: 'c-shrinkage', label: 'Shrinkage', category: 'ManufacturingConcepts', definition: 'Dimensional change of fabric after wash/steam; drives cutting recipe.', moduleRefs: ['product-card', 'cutting'], tags: ['fabric'] },
  { id: 'c-recipe', label: 'Cutting Recipe', category: 'ManufacturingConcepts', definition: 'Lay/marker parameters including shrinkage allowance and layers.', moduleRefs: ['cutting'], tags: ['cutting'] },
  { id: 'c-cutting', label: 'Cutting', category: 'ProductionFlows', definition: 'Marker, lay, and cut operations producing bundles.', moduleRefs: ['cutting', 'production-order'], tags: ['cutting'] },
  { id: 'c-sewing', label: 'Sewing', category: 'ProductionFlows', definition: 'Assembly operations at work centers using SAM/SMV.', moduleRefs: ['shop-floor', 'production-order'], tags: ['sewing'] },
  { id: 'c-quality', label: 'Quality', category: 'QualityRules', definition: 'Inline/final inspection, AQL, FTT, hold/rework gates.', moduleRefs: ['quality'], tags: ['quality'] },
  { id: 'c-packing', label: 'Packing', category: 'ProductionFlows', definition: 'Carton/packing list confirmation before shipment.', moduleRefs: ['packaging'], tags: ['packing'] },
  { id: 'c-shipment', label: 'Shipment', category: 'ShipmentRules', definition: 'Dispatch of finished goods against packing and commercial docs.', moduleRefs: ['shipment', 'export-logistics'], tags: ['shipping'] },
  { id: 'c-order', label: 'Sales Order', category: 'ManufacturingConcepts', definition: 'Customer demand document driving MRP and production.', moduleRefs: ['sales-order'], tags: ['order'] },
  { id: 'c-product', label: 'Product Card', category: 'ManufacturingConcepts', definition: 'Style master with BOM, route, and cost sheet children.', moduleRefs: ['product-card'], tags: ['style'] },
  { id: 'c-bom', label: 'BOM', category: 'ManufacturingConcepts', definition: 'Bill of materials for fabric and trim consumption.', moduleRefs: ['bom'], tags: ['bom'] },
  { id: 'c-mrp', label: 'MRP', category: 'PlanningRules', definition: 'Material requirements planning from gross demand to net need.', moduleRefs: ['mrp'], tags: ['planning'] },
  { id: 'c-purchasing', label: 'Purchasing', category: 'PurchasingRules', definition: 'PR/RFQ/PO/GR cycle for materials.', moduleRefs: ['purchasing'], tags: ['purchasing'] },
  { id: 'c-receiving', label: 'Receiving', category: 'WarehouseRules', definition: 'Goods receipt posting into stock ledger.', moduleRefs: ['inventory', 'warehouse'], tags: ['warehouse'] },
  { id: 'c-warehouse', label: 'Warehouse', category: 'WarehouseRules', definition: 'Storage, reservation, transfer, and FIFO lot control.', moduleRefs: ['warehouse', 'inventory'], tags: ['warehouse'] },
  { id: 'c-finance', label: 'Finance', category: 'FinanceRules', definition: 'Operational events to journal posting and closing.', moduleRefs: ['finance-integration', 'cost-closing'], tags: ['finance'] },
  { id: 'c-lot', label: 'Lot', category: 'TextileTerminology', definition: 'Traceable material batch identity for FIFO and quality.', moduleRefs: ['inventory'], tags: ['lot'] },
  { id: 'c-batch', label: 'Batch', category: 'TextileTerminology', definition: 'Production or dye lot grouping.', moduleRefs: ['production-order'], tags: ['batch'] },
  { id: 'c-marker', label: 'Marker', category: 'TextileTerminology', definition: 'Cutting layout of pattern pieces on fabric width.', moduleRefs: ['cutting'], tags: ['cutting'] },
  { id: 'c-lay', label: 'Lay', category: 'TextileTerminology', definition: 'Stacked fabric plies prepared for cutting.', moduleRefs: ['cutting'], tags: ['cutting'] },
  { id: 'c-bundle', label: 'Bundle', category: 'TextileTerminology', definition: 'Tied cut components tracked through sewing.', moduleRefs: ['execution-platform', 'barcode-mobile'], tags: ['bundle'] },
  { id: 'c-sam', label: 'SAM', category: 'TextileTerminology', definition: 'Standard Allowed Minutes for an operation.', moduleRefs: ['shop-floor'], tags: ['ie'] },
  { id: 'c-smv', label: 'SMV', category: 'TextileTerminology', definition: 'Standard Minute Value — engineered time standard.', moduleRefs: ['shop-floor'], tags: ['ie'] },
  { id: 'c-oee', label: 'OEE', category: 'KpiLibrary', definition: 'Overall Equipment Effectiveness.', moduleRefs: ['shop-floor'], tags: ['kpi'] },
  { id: 'c-ftt', label: 'FTT', category: 'KpiLibrary', definition: 'First Time Through quality yield.', moduleRefs: ['quality'], tags: ['kpi'] },
  { id: 'c-aql', label: 'AQL', category: 'QualityRules', definition: 'Acceptable Quality Limit sampling plan.', moduleRefs: ['quality'], tags: ['quality'] },
  { id: 'c-routing', label: 'Routing', category: 'ManufacturingConcepts', definition: 'Ordered operations for a style.', moduleRefs: ['product-card', 'production-order'], tags: ['routing'] },
  { id: 'c-work-center', label: 'Work Center', category: 'ManufacturingConcepts', definition: 'Capacity-bearing resource group of machines/operators.', moduleRefs: ['production-planning'], tags: ['capacity'] },
  { id: 'c-fifo', label: 'FIFO', category: 'InventoryRules', definition: 'First-in first-out lot consumption policy.', moduleRefs: ['inventory'], tags: ['inventory'] },
  { id: 'c-waste', label: 'Waste', category: 'CostRules', definition: 'Material loss vs standard allowance.', moduleRefs: ['cost-sheet', 'cutting'], tags: ['cost'] },
]

export const KNOWLEDGE_EDGES: KnowledgeConceptEdge[] = [
  { id: 'e1', fromId: 'c-cotton', toId: 'c-shrinkage', relation: 'REQUIRES', label: 'has shrinkage' },
  { id: 'e2', fromId: 'c-shrinkage', toId: 'c-recipe', relation: 'ENABLES', label: 'feeds recipe' },
  { id: 'e3', fromId: 'c-recipe', toId: 'c-cutting', relation: 'PRECEDES' },
  { id: 'e4', fromId: 'c-cutting', toId: 'c-sewing', relation: 'PRECEDES' },
  { id: 'e5', fromId: 'c-sewing', toId: 'c-quality', relation: 'PRECEDES' },
  { id: 'e6', fromId: 'c-quality', toId: 'c-packing', relation: 'PRECEDES' },
  { id: 'e7', fromId: 'c-packing', toId: 'c-shipment', relation: 'PRECEDES' },
  { id: 'e8', fromId: 'c-order', toId: 'c-product', relation: 'REQUIRES' },
  { id: 'e9', fromId: 'c-product', toId: 'c-bom', relation: 'REQUIRES' },
  { id: 'e10', fromId: 'c-bom', toId: 'c-mrp', relation: 'TRIGGERS_DECISION' },
  { id: 'e11', fromId: 'c-mrp', toId: 'c-purchasing', relation: 'TRIGGERS_DECISION' },
  { id: 'e12', fromId: 'c-purchasing', toId: 'c-receiving', relation: 'PRECEDES' },
  { id: 'e13', fromId: 'c-receiving', toId: 'c-warehouse', relation: 'PRODUCES' },
  { id: 'e14', fromId: 'c-warehouse', toId: 'c-cutting', relation: 'ENABLES' },
  { id: 'e15', fromId: 'c-shipment', toId: 'c-finance', relation: 'TRIGGERS_DECISION' },
  { id: 'e16', fromId: 'c-cutting', toId: 'c-bundle', relation: 'PRODUCES' },
  { id: 'e17', fromId: 'c-bundle', toId: 'c-sewing', relation: 'CONSUMES' },
  { id: 'e18', fromId: 'c-marker', toId: 'c-cutting', relation: 'APPLIES_TO' },
  { id: 'e19', fromId: 'c-lay', toId: 'c-cutting', relation: 'APPLIES_TO' },
  { id: 'e20', fromId: 'c-fifo', toId: 'c-warehouse', relation: 'CONSTRAINS' },
  { id: 'e21', fromId: 'c-aql', toId: 'c-quality', relation: 'CONSTRAINS' },
  { id: 'e22', fromId: 'c-sam', toId: 'c-sewing', relation: 'MEASURES' },
  { id: 'e23', fromId: 'c-oee', toId: 'c-work-center', relation: 'MEASURES' },
  { id: 'e24', fromId: 'c-ftt', toId: 'c-quality', relation: 'MEASURES' },
  { id: 'e25', fromId: 'c-waste', toId: 'c-cutting', relation: 'MEASURES' },
]

export const FORMULAE: FormulaDefinition[] = [
  {
    id: 'f-efficiency',
    code: 'EFFICIENCY',
    name: 'Labor Efficiency',
    category: 'CalculationFormulae',
    expression: 'producedMinutes / availableWorkerMinutes',
    evaluatorId: 'div',
    parameters: [
      { name: 'production', unit: 'min', required: true, description: 'Produced standard minutes' },
      { name: 'worker', unit: 'min', required: true, description: 'Available worker minutes' },
    ],
    resultUnit: 'ratio',
    relatedConcepts: ['c-sam', 'c-sewing'],
    explanation: 'Efficiency = Production / Worker',
  },
  {
    id: 'f-cutting-cost',
    code: 'CUTTING_COST_UNIT',
    name: 'Unit Cutting Cost',
    category: 'CostRules',
    expression: 'totalCuttingCost / quantity',
    evaluatorId: 'div',
    parameters: [
      { name: 'totalCuttingCost', unit: 'currency', required: true, description: 'Total cutting cost' },
      { name: 'quantity', unit: 'pcs', required: true, description: 'Cut quantity' },
    ],
    resultUnit: 'currency/pcs',
    relatedConcepts: ['c-cutting', 'c-waste'],
    explanation: 'Cutting Cost = Total Cutting Cost / Quantity',
  },
  {
    id: 'f-marker-eff',
    code: 'MARKER_EFFICIENCY',
    name: 'Marker Efficiency',
    category: 'CalculationFormulae',
    expression: 'templateArea / markerArea',
    evaluatorId: 'div',
    parameters: [
      { name: 'templateArea', unit: 'm2', required: true, description: 'Sum of piece areas' },
      { name: 'markerArea', unit: 'm2', required: true, description: 'Marker length × width' },
    ],
    resultUnit: 'ratio',
    relatedConcepts: ['c-marker', 'c-cutting'],
    explanation: 'Marker Efficiency = Template Area / Marker Area',
  },
  {
    id: 'f-top-end',
    code: 'TOP_END',
    name: 'Top End (roll remnant)',
    category: 'CalculationFormulae',
    expression: 'rollLength - markerLength * layers',
    evaluatorId: 'top_end',
    parameters: [
      { name: 'rollLength', unit: 'm', required: true, description: 'Fabric roll length' },
      { name: 'markerLength', unit: 'm', required: true, description: 'Marker length' },
      { name: 'layers', unit: 'plies', required: true, description: 'Lay layers' },
    ],
    resultUnit: 'm',
    relatedConcepts: ['c-lay', 'c-marker', 'c-cotton'],
    explanation: 'Top End = Roll Length - Marker Length × Layers',
  },
  {
    id: 'f-mrp-net',
    code: 'MRP_NET_REQUIREMENT',
    name: 'MRP Net Requirement',
    category: 'PlanningRules',
    expression: 'gross - stock - openPO - openProduction',
    evaluatorId: 'mrp_net',
    parameters: [
      { name: 'gross', unit: 'uom', required: true, description: 'Gross requirement' },
      { name: 'stock', unit: 'uom', required: true, description: 'On-hand stock' },
      { name: 'openPO', unit: 'uom', required: true, description: 'Open purchase orders' },
      { name: 'openProduction', unit: 'uom', required: true, description: 'Open production supply' },
    ],
    resultUnit: 'uom',
    relatedConcepts: ['c-mrp', 'c-purchasing', 'c-warehouse'],
    explanation: 'MRP = Gross - Stock - Open PO - Open Production',
  },
  {
    id: 'f-oee',
    code: 'OEE',
    name: 'OEE',
    category: 'KpiLibrary',
    expression: 'availability * performance * quality',
    evaluatorId: 'product3',
    parameters: [
      { name: 'availability', unit: 'ratio', required: true, description: 'Availability' },
      { name: 'performance', unit: 'ratio', required: true, description: 'Performance' },
      { name: 'quality', unit: 'ratio', required: true, description: 'Quality yield' },
    ],
    resultUnit: 'ratio',
    relatedConcepts: ['c-oee', 'c-work-center'],
    explanation: 'OEE = Availability × Performance × Quality',
  },
  {
    id: 'f-ftt',
    code: 'FTT',
    name: 'First Time Through',
    category: 'KpiLibrary',
    expression: 'goodFirstPass / totalInspected',
    evaluatorId: 'div',
    parameters: [
      { name: 'goodFirstPass', unit: 'pcs', required: true, description: 'Passed first inspection' },
      { name: 'totalInspected', unit: 'pcs', required: true, description: 'Total inspected' },
    ],
    resultUnit: 'ratio',
    relatedConcepts: ['c-ftt', 'c-quality'],
    explanation: 'FTT = Good First Pass / Total Inspected',
  },
  {
    id: 'f-waste-pct',
    code: 'WASTE_PCT',
    name: 'Waste Percent',
    category: 'CostRules',
    expression: 'wasteQty / issuedQty',
    evaluatorId: 'div',
    parameters: [
      { name: 'wasteQty', unit: 'uom', required: true, description: 'Waste quantity' },
      { name: 'issuedQty', unit: 'uom', required: true, description: 'Issued quantity' },
    ],
    resultUnit: 'ratio',
    relatedConcepts: ['c-waste', 'c-cutting'],
    explanation: 'Waste % = Waste / Issued',
  },
]

export const BUSINESS_RULES: BusinessRuleDefinition[] = [
  {
    id: 'br-fifo',
    code: 'FIFO_CONSUME_OLDEST',
    name: 'FIFO lot consumption',
    category: 'InventoryRules',
    when: [{ field: 'fifoEnabled', operator: 'IS_TRUE' }],
    then: [{ type: 'REQUIRE_LOT_FIFO', message: 'Consume oldest lot first.' }],
    relatedConcepts: ['c-fifo', 'c-lot', 'c-warehouse'],
    severity: 'WARNING',
    explanation: 'IF FIFO enabled THEN consume oldest lot.',
  },
  {
    id: 'br-roll-vs-marker',
    code: 'ROLL_SHORTER_THAN_MARKER',
    name: 'Reject short fabric roll',
    category: 'QualityRules',
    when: [{ field: 'rollLength', operator: 'LT', value: 'markerLength' }],
    then: [{ type: 'REJECT', message: 'Fabric roll shorter than marker length.' }],
    relatedConcepts: ['c-cotton', 'c-marker', 'c-cutting'],
    severity: 'CRITICAL',
    explanation: 'IF Fabric Roll < Marker Length THEN Reject.',
  },
  {
    id: 'br-waste-alert',
    code: 'WASTE_OVER_STANDARD',
    name: 'Waste over standard alert',
    category: 'CostRules',
    when: [{ field: 'wastePct', operator: 'GT', value: 'standardWastePct' }],
    then: [{ type: 'ALERT', message: 'Generate Production Alert — waste exceeds standard.', target: 'production' }],
    relatedConcepts: ['c-waste', 'c-cutting'],
    severity: 'WARNING',
    explanation: 'IF Waste > Standard Waste THEN Generate Production Alert.',
  },
  {
    id: 'br-maint',
    code: 'MAINTENANCE_EXPIRED_BLOCK',
    name: 'Block machine on expired maintenance',
    category: 'BusinessRules',
    when: [{ field: 'maintenanceExpired', operator: 'IS_TRUE' }],
    then: [{ type: 'BLOCK_MACHINE', message: 'Machine cannot receive new Production Orders.' }],
    relatedConcepts: ['c-work-center', 'c-sewing'],
    severity: 'CRITICAL',
    explanation: 'IF Machine Maintenance Expired THEN block new POs.',
  },
  {
    id: 'br-insp-fail',
    code: 'INSPECTION_FAIL_BLOCK_SHIP',
    name: 'Block shipment on failed inspection',
    category: 'ShipmentRules',
    when: [{ field: 'inspectionFailed', operator: 'IS_TRUE' }],
    then: [{ type: 'BLOCK_SHIPMENT', message: 'Shipment cannot continue.' }],
    relatedConcepts: ['c-quality', 'c-shipment', 'c-aql'],
    severity: 'CRITICAL',
    explanation: 'IF Inspection Failed THEN Shipment cannot continue.',
  },
]

export const DICTIONARY: DictionaryEntry[] = [
  { id: 'd-lot', term: 'Lot', category: 'TextileTerminology', definition: 'Traceable material identity used for FIFO and recalls.', relatedModules: ['inventory'], relatedConcepts: ['c-lot', 'c-fifo'], typicalCalculations: ['f-mrp-net'], typicalDecisions: ['dec-low-stock'], aliases: ['batch-lot'] },
  { id: 'd-batch', term: 'Batch', category: 'TextileTerminology', definition: 'Grouped production or process lot.', relatedModules: ['production-order'], relatedConcepts: ['c-batch'], typicalCalculations: [], typicalDecisions: [], aliases: [] },
  { id: 'd-marker', term: 'Marker', category: 'TextileTerminology', definition: 'Nesting layout of garment pieces on fabric.', relatedModules: ['cutting'], relatedConcepts: ['c-marker'], typicalCalculations: ['f-marker-eff', 'f-top-end'], typicalDecisions: [], aliases: ['cut-marker'] },
  { id: 'd-lay', term: 'Lay', category: 'TextileTerminology', definition: 'Multi-ply fabric stack prepared for cutting.', relatedModules: ['cutting'], relatedConcepts: ['c-lay'], typicalCalculations: ['f-top-end'], typicalDecisions: [], aliases: ['spread'] },
  { id: 'd-bundle', term: 'Bundle', category: 'TextileTerminology', definition: 'Tied cut parts tracked on the sewing floor.', relatedModules: ['execution-platform', 'barcode-mobile'], relatedConcepts: ['c-bundle'], typicalCalculations: [], typicalDecisions: [], aliases: ['bundle-card'] },
  { id: 'd-interlining', term: 'Interlining', category: 'TextileTerminology', definition: 'Stabilizing fabric fused or sewn into garments.', relatedModules: ['product-card', 'bom'], relatedConcepts: ['c-bom'], typicalCalculations: [], typicalDecisions: [], aliases: ['fusing'] },
  { id: 'd-shrinkage', term: 'Shrinkage', category: 'ManufacturingConcepts', definition: 'Expected fabric dimensional change.', relatedModules: ['cutting', 'product-card'], relatedConcepts: ['c-shrinkage', 'c-recipe'], typicalCalculations: [], typicalDecisions: [], aliases: [] },
  { id: 'd-sam', term: 'SAM', category: 'TextileTerminology', definition: 'Standard Allowed Minutes.', relatedModules: ['shop-floor'], relatedConcepts: ['c-sam'], typicalCalculations: ['f-efficiency'], typicalDecisions: ['dec-late-order'], aliases: [] },
  { id: 'd-smv', term: 'SMV', category: 'TextileTerminology', definition: 'Standard Minute Value.', relatedModules: ['shop-floor'], relatedConcepts: ['c-smv'], typicalCalculations: ['f-efficiency'], typicalDecisions: [], aliases: [] },
  { id: 'd-oee', term: 'OEE', category: 'KpiLibrary', definition: 'Overall Equipment Effectiveness.', relatedModules: ['shop-floor'], relatedConcepts: ['c-oee'], typicalCalculations: ['f-oee'], typicalDecisions: ['dec-late-order'], aliases: [] },
  { id: 'd-ftt', term: 'FTT', category: 'KpiLibrary', definition: 'First Time Through.', relatedModules: ['quality'], relatedConcepts: ['c-ftt'], typicalCalculations: ['f-ftt'], typicalDecisions: [], aliases: ['FTY'] },
  { id: 'd-spc', term: 'SPC', category: 'QualityRules', definition: 'Statistical Process Control.', relatedModules: ['quality'], relatedConcepts: ['c-quality'], typicalCalculations: [], typicalDecisions: [], aliases: [] },
  { id: 'd-aql', term: 'AQL', category: 'QualityRules', definition: 'Acceptable Quality Limit.', relatedModules: ['quality'], relatedConcepts: ['c-aql'], typicalCalculations: [], typicalDecisions: [], aliases: [] },
  { id: 'd-mrp', term: 'MRP', category: 'PlanningRules', definition: 'Material Requirements Planning.', relatedModules: ['mrp'], relatedConcepts: ['c-mrp'], typicalCalculations: ['f-mrp-net'], typicalDecisions: ['dec-low-stock'], aliases: [] },
  { id: 'd-aps', term: 'APS', category: 'PlanningRules', definition: 'Advanced Planning and Scheduling.', relatedModules: ['production-planning'], relatedConcepts: ['c-work-center'], typicalCalculations: [], typicalDecisions: ['dec-late-order'], aliases: [] },
  { id: 'd-routing', term: 'Routing', category: 'ManufacturingConcepts', definition: 'Sequence of operations for a style.', relatedModules: ['product-card'], relatedConcepts: ['c-routing'], typicalCalculations: [], typicalDecisions: [], aliases: ['route'] },
  { id: 'd-bom', term: 'BOM', category: 'ManufacturingConcepts', definition: 'Bill of Materials.', relatedModules: ['bom'], relatedConcepts: ['c-bom'], typicalCalculations: ['f-mrp-net'], typicalDecisions: [], aliases: [] },
  { id: 'd-wc', term: 'Work Center', category: 'ManufacturingConcepts', definition: 'Capacity resource for scheduling.', relatedModules: ['production-planning'], relatedConcepts: ['c-work-center'], typicalCalculations: ['f-oee'], typicalDecisions: ['dec-late-order'], aliases: ['workcentre'] },
  { id: 'd-kanban', term: 'Kanban', category: 'ManufacturingConcepts', definition: 'Pull signal for replenishment.', relatedModules: ['inventory'], relatedConcepts: ['c-warehouse'], typicalCalculations: [], typicalDecisions: ['dec-low-stock'], aliases: [] },
  { id: 'd-rfid', term: 'RFID', category: 'TextileTerminology', definition: 'Radio identification for bundles/cartons.', relatedModules: ['barcode-mobile'], relatedConcepts: ['c-bundle'], typicalCalculations: [], typicalDecisions: [], aliases: [] },
  { id: 'd-mes', term: 'MES', category: 'ManufacturingConcepts', definition: 'Manufacturing Execution System layer (shop floor).', relatedModules: ['shop-floor', 'execution-platform'], relatedConcepts: ['c-sewing'], typicalCalculations: ['f-efficiency'], typicalDecisions: [], aliases: [] },
  { id: 'd-ob', term: 'Operation Bulletin', category: 'ManufacturingConcepts', definition: 'List of operations with SAM and machines.', relatedModules: ['product-card'], relatedConcepts: ['c-routing', 'c-sam'], typicalCalculations: [], typicalDecisions: [], aliases: ['OB'] },
  { id: 'd-needle-gauge', term: 'Needle Gauge', category: 'TextileTerminology', definition: 'Needle size designation for machine setup.', relatedModules: ['shop-floor'], relatedConcepts: ['c-sewing'], typicalCalculations: [], typicalDecisions: [], aliases: [] },
  { id: 'd-gauge', term: 'Gauge', category: 'TextileTerminology', definition: 'Needle density / knitting machine gauge.', relatedModules: ['product-card'], relatedConcepts: ['c-product'], typicalCalculations: [], typicalDecisions: [], aliases: [] },
  { id: 'd-needle-density', term: 'Needle Density', category: 'TextileTerminology', definition: 'Needles per unit length on knitting equipment.', relatedModules: ['product-card'], relatedConcepts: ['c-product'], typicalCalculations: [], typicalDecisions: [], aliases: [] },
  { id: 'd-seam', term: 'Seam Type', category: 'TextileTerminology', definition: 'ISO seam class used in construction.', relatedModules: ['product-card', 'quality'], relatedConcepts: ['c-sewing', 'c-quality'], typicalCalculations: [], typicalDecisions: [], aliases: [] },
  { id: 'd-bundle-card', term: 'Bundle Card', category: 'TextileTerminology', definition: 'Physical/digital ticket identifying a bundle.', relatedModules: ['barcode-mobile'], relatedConcepts: ['c-bundle'], typicalCalculations: [], typicalDecisions: [], aliases: ['work-ticket'] },
  { id: 'd-work-ticket', term: 'Work Ticket', category: 'TextileTerminology', definition: 'Instruction ticket for an operation/bundle.', relatedModules: ['shop-floor'], relatedConcepts: ['c-bundle', 'c-sewing'], typicalCalculations: [], typicalDecisions: [], aliases: ['bundle-card'] },
]

export const FLOWS: ProductionFlowDefinition[] = [
  {
    id: 'flow-end-to-end',
    code: 'ORDER_TO_FINANCE',
    name: 'Order → Finance textile flow',
    description: 'Canonical end-to-end apparel manufacturing flow.',
    steps: [
      { id: 's1', sequence: 1, conceptId: 'c-order', label: 'Order', moduleRef: 'sales-order' },
      { id: 's2', sequence: 2, conceptId: 'c-product', label: 'Product', moduleRef: 'product-card' },
      { id: 's3', sequence: 3, conceptId: 'c-bom', label: 'BOM', moduleRef: 'bom' },
      { id: 's4', sequence: 4, conceptId: 'c-mrp', label: 'MRP', moduleRef: 'mrp' },
      { id: 's5', sequence: 5, conceptId: 'c-purchasing', label: 'Purchasing', moduleRef: 'purchasing' },
      { id: 's6', sequence: 6, conceptId: 'c-receiving', label: 'Receiving', moduleRef: 'inventory' },
      { id: 's7', sequence: 7, conceptId: 'c-warehouse', label: 'Warehouse', moduleRef: 'warehouse' },
      { id: 's8', sequence: 8, conceptId: 'c-cutting', label: 'Cutting', moduleRef: 'cutting' },
      { id: 's9', sequence: 9, conceptId: 'c-sewing', label: 'Sewing', moduleRef: 'shop-floor' },
      { id: 's10', sequence: 10, conceptId: 'c-quality', label: 'Quality', moduleRef: 'quality' },
      { id: 's11', sequence: 11, conceptId: 'c-packing', label: 'Packing', moduleRef: 'packaging' },
      { id: 's12', sequence: 12, conceptId: 'c-shipment', label: 'Shipment', moduleRef: 'shipment' },
      { id: 's13', sequence: 13, conceptId: 'c-finance', label: 'Finance', moduleRef: 'finance-integration' },
    ],
  },
  {
    id: 'flow-fabric-path',
    code: 'FABRIC_TO_SHIP',
    name: 'Cotton → Shipment path',
    description: 'Material science path from fabric properties through shipment.',
    steps: [
      { id: 'fs1', sequence: 1, conceptId: 'c-cotton', label: 'Cotton Fabric' },
      { id: 'fs2', sequence: 2, conceptId: 'c-shrinkage', label: 'Shrinkage' },
      { id: 'fs3', sequence: 3, conceptId: 'c-recipe', label: 'Recipe' },
      { id: 'fs4', sequence: 4, conceptId: 'c-cutting', label: 'Cutting' },
      { id: 'fs5', sequence: 5, conceptId: 'c-sewing', label: 'Sewing' },
      { id: 'fs6', sequence: 6, conceptId: 'c-quality', label: 'Quality' },
      { id: 'fs7', sequence: 7, conceptId: 'c-packing', label: 'Packing' },
      { id: 'fs8', sequence: 8, conceptId: 'c-shipment', label: 'Shipment' },
    ],
  },
]

export const DECISIONS: DecisionDefinition[] = [
  {
    id: 'dec-low-stock',
    code: 'LOW_STOCK',
    trigger: 'Low Stock',
    name: 'Low stock replenishment path',
    category: 'DecisionRules',
    steps: [
      { id: 'ds1', sequence: 1, action: 'Check Open PO', conceptId: 'c-purchasing', outcomeHint: 'Identify inbound supply' },
      { id: 'ds2', sequence: 2, action: 'Check Safety Stock', conceptId: 'c-warehouse', outcomeHint: 'Compare vs policy' },
      { id: 'ds3', sequence: 3, action: 'Suggest Purchase', conceptId: 'c-mrp', outcomeHint: 'Raise PR/PO suggestion' },
    ],
    relatedConcepts: ['c-warehouse', 'c-purchasing', 'c-mrp'],
    relatedKpis: ['kpi-otif'],
  },
  {
    id: 'dec-late-order',
    code: 'LATE_ORDER',
    trigger: 'Late Order',
    name: 'Late order recovery path',
    category: 'DecisionRules',
    steps: [
      { id: 'dl1', sequence: 1, action: 'Check Capacity', conceptId: 'c-work-center', outcomeHint: 'Available vs load' },
      { id: 'dl2', sequence: 2, action: 'Suggest Overtime', outcomeHint: 'Extend calendar capacity' },
      { id: 'dl3', sequence: 3, action: 'Suggest Alternate Work Center', conceptId: 'c-work-center', outcomeHint: 'Rebalance load' },
      { id: 'dl4', sequence: 4, action: 'Suggest Partial Shipment', conceptId: 'c-shipment', outcomeHint: 'Ship available FG' },
    ],
    relatedConcepts: ['c-order', 'c-sewing', 'c-shipment'],
    relatedKpis: ['kpi-otif', 'kpi-utilization'],
  },
]

export const MACHINES: MachineDefinition[] = [
  { id: 'm-sn', code: 'SINGLE_NEEDLE', name: 'Single Needle', capabilities: ['lockstitch'], supportedOperations: ['op-sew-side', 'op-topstitch'], setupTimeMinutes: 5, maintenanceRules: ['br-maint'], capacityUnitsPerHour: 120, relatedOperations: ['op-sew-side'], relatedConcepts: ['c-sewing'] },
  { id: 'm-ol', code: 'OVERLOCK', name: 'Overlock', capabilities: ['overedge', 'safety-stitch'], supportedOperations: ['op-overlock'], setupTimeMinutes: 8, maintenanceRules: ['br-maint'], capacityUnitsPerHour: 140, relatedOperations: ['op-overlock'], relatedConcepts: ['c-sewing'] },
  { id: 'm-cs', code: 'COVERSTITCH', name: 'Coverstitch', capabilities: ['cover', 'hemming'], supportedOperations: ['op-hem'], setupTimeMinutes: 10, maintenanceRules: ['br-maint'], capacityUnitsPerHour: 100, relatedOperations: ['op-hem'], relatedConcepts: ['c-sewing'] },
  { id: 'm-bh', code: 'BUTTONHOLE', name: 'Buttonhole', capabilities: ['buttonhole'], supportedOperations: ['op-buttonhole'], setupTimeMinutes: 12, maintenanceRules: ['br-maint'], capacityUnitsPerHour: 80, relatedOperations: ['op-buttonhole'], relatedConcepts: ['c-sewing'] },
  { id: 'm-ba', code: 'BUTTON_ATTACH', name: 'Button Attach', capabilities: ['button-sew'], supportedOperations: ['op-button-attach'], setupTimeMinutes: 10, maintenanceRules: ['br-maint'], capacityUnitsPerHour: 90, relatedOperations: ['op-button-attach'], relatedConcepts: ['c-sewing'] },
  { id: 'm-cut', code: 'AUTO_CUTTER', name: 'Automatic Cutter', capabilities: ['cut', 'notch'], supportedOperations: ['op-cut'], setupTimeMinutes: 20, maintenanceRules: ['br-maint'], capacityUnitsPerHour: 200, relatedOperations: ['op-cut'], relatedConcepts: ['c-cutting', 'c-marker'] },
  { id: 'm-plot', code: 'PLOTTER', name: 'Plotter', capabilities: ['plot-marker'], supportedOperations: ['op-plot'], setupTimeMinutes: 5, maintenanceRules: ['br-maint'], capacityUnitsPerHour: 40, relatedOperations: ['op-plot'], relatedConcepts: ['c-marker'] },
  { id: 'm-press', code: 'STEAM_PRESS', name: 'Steam Press', capabilities: ['press', 'finish'], supportedOperations: ['op-press'], setupTimeMinutes: 6, maintenanceRules: ['br-maint'], capacityUnitsPerHour: 110, relatedOperations: ['op-press'], relatedConcepts: ['c-sewing', 'c-quality'] },
  { id: 'm-emb', code: 'EMBROIDERY', name: 'Embroidery', capabilities: ['embroidery'], supportedOperations: ['op-embroidery'], setupTimeMinutes: 25, maintenanceRules: ['br-maint'], capacityUnitsPerHour: 30, relatedOperations: ['op-embroidery'], relatedConcepts: ['c-sewing'] },
  { id: 'm-print', code: 'TRANSFER_PRINT', name: 'Transfer Printing', capabilities: ['print'], supportedOperations: ['op-print'], setupTimeMinutes: 15, maintenanceRules: ['br-maint'], capacityUnitsPerHour: 50, relatedOperations: ['op-print'], relatedConcepts: ['c-product'] },
]

export const OPERATIONS: OperationDefinition[] = [
  { id: 'op-cut', code: 'CUT', name: 'Cut', description: 'Cut plies per marker', typicalMachines: ['m-cut'], relatedConcepts: ['c-cutting'] },
  { id: 'op-plot', code: 'PLOT', name: 'Plot Marker', description: 'Plot marker on paper/fabric', typicalMachines: ['m-plot'], relatedConcepts: ['c-marker'] },
  { id: 'op-sew-side', code: 'SEW_SIDE', name: 'Sew Side Seam', description: 'Join side seams', typicalMachines: ['m-sn'], relatedConcepts: ['c-sewing', 'c-sam'] },
  { id: 'op-overlock', code: 'OVERLOCK', name: 'Overlock Edge', description: 'Overedge finish', typicalMachines: ['m-ol'], relatedConcepts: ['c-sewing'] },
  { id: 'op-hem', code: 'HEM', name: 'Hem', description: 'Coverstitch hem', typicalMachines: ['m-cs'], relatedConcepts: ['c-sewing'] },
  { id: 'op-buttonhole', code: 'BUTTONHOLE', name: 'Buttonhole', description: 'Make buttonholes', typicalMachines: ['m-bh'], relatedConcepts: ['c-sewing'] },
  { id: 'op-button-attach', code: 'BUTTON_ATTACH', name: 'Button Attach', description: 'Sew buttons', typicalMachines: ['m-ba'], relatedConcepts: ['c-sewing'] },
  { id: 'op-press', code: 'PRESS', name: 'Press', description: 'Steam press finish', typicalMachines: ['m-press'], relatedConcepts: ['c-quality'] },
  { id: 'op-embroidery', code: 'EMBROIDERY', name: 'Embroidery', description: 'Embroider logo/motif', typicalMachines: ['m-emb'], relatedConcepts: ['c-sewing'] },
  { id: 'op-print', code: 'PRINT', name: 'Transfer Print', description: 'Apply transfer print', typicalMachines: ['m-print'], relatedConcepts: ['c-product'] },
]

export const KPIS: KpiDefinition[] = [
  { id: 'kpi-efficiency', code: 'EFFICIENCY', name: 'Efficiency', formulaId: 'f-efficiency', target: 0.85, warningLevel: 0.75, criticalLevel: 0.65, unit: 'ratio', higherIsBetter: true, recommendationLogic: 'IF below warning THEN check SAM vs method AND suggest overtime or alternate WC', relatedConcepts: ['c-sam', 'c-sewing'] },
  { id: 'kpi-oee', code: 'OEE', name: 'OEE', formulaId: 'f-oee', target: 0.75, warningLevel: 0.65, criticalLevel: 0.55, unit: 'ratio', higherIsBetter: true, recommendationLogic: 'Decompose availability/performance/quality losses', relatedConcepts: ['c-oee'] },
  { id: 'kpi-ftt', code: 'FTT', name: 'FTT', formulaId: 'f-ftt', target: 0.95, warningLevel: 0.9, criticalLevel: 0.85, unit: 'ratio', higherIsBetter: true, recommendationLogic: 'IF critical THEN hold shipment path and raise rework', relatedConcepts: ['c-ftt', 'c-quality'] },
  { id: 'kpi-wip', code: 'WIP', name: 'WIP', formulaId: 'f-efficiency', target: 1, warningLevel: 1.2, criticalLevel: 1.5, unit: 'days', higherIsBetter: false, recommendationLogic: 'High WIP → pull bundles / balance line', relatedConcepts: ['c-bundle', 'c-sewing'] },
  { id: 'kpi-lead', code: 'LEAD_TIME', name: 'Lead Time', formulaId: 'f-efficiency', target: 14, warningLevel: 18, criticalLevel: 21, unit: 'days', higherIsBetter: false, recommendationLogic: 'Late → LATE_ORDER decision tree', relatedConcepts: ['c-order'] },
  { id: 'kpi-cycle', code: 'CYCLE_TIME', name: 'Cycle Time', formulaId: 'f-efficiency', target: 1, warningLevel: 1.3, criticalLevel: 1.6, unit: 'min', higherIsBetter: false, recommendationLogic: 'Review bottleneck operation SAM', relatedConcepts: ['c-sam'] },
  { id: 'kpi-utilization', code: 'UTILIZATION', name: 'Utilization', formulaId: 'f-efficiency', target: 0.9, warningLevel: 0.7, criticalLevel: 0.5, unit: 'ratio', higherIsBetter: true, recommendationLogic: 'Low util → rebalance or accept more load', relatedConcepts: ['c-work-center'] },
  { id: 'kpi-capacity', code: 'CAPACITY', name: 'Capacity', formulaId: 'f-efficiency', target: 1, warningLevel: 0.85, criticalLevel: 0.7, unit: 'ratio', higherIsBetter: true, recommendationLogic: 'Overload → overtime or alternate WC', relatedConcepts: ['c-work-center'] },
  { id: 'kpi-waste', code: 'WASTE_PCT', name: 'Waste %', formulaId: 'f-waste-pct', target: 0.03, warningLevel: 0.05, criticalLevel: 0.08, unit: 'ratio', higherIsBetter: false, recommendationLogic: 'IF over standard THEN Production Alert', relatedConcepts: ['c-waste'] },
  { id: 'kpi-rework', code: 'REWORK_PCT', name: 'Rework %', formulaId: 'f-ftt', target: 0.03, warningLevel: 0.05, criticalLevel: 0.08, unit: 'ratio', higherIsBetter: false, recommendationLogic: 'Raise quality hold and method audit', relatedConcepts: ['c-quality'] },
  { id: 'kpi-scrap', code: 'SCRAP_PCT', name: 'Scrap %', formulaId: 'f-waste-pct', target: 0.01, warningLevel: 0.02, criticalLevel: 0.04, unit: 'ratio', higherIsBetter: false, recommendationLogic: 'Block shipment if inspection failed', relatedConcepts: ['c-quality'] },
  { id: 'kpi-otif', code: 'OTIF', name: 'OTIF', formulaId: 'f-efficiency', target: 0.95, warningLevel: 0.9, criticalLevel: 0.85, unit: 'ratio', higherIsBetter: true, recommendationLogic: 'Late → LATE_ORDER decision; Low stock → LOW_STOCK', relatedConcepts: ['c-shipment', 'c-order'] },
]

export const REASONING_SCHEMA: ReasoningSchema = {
  schemaVersion: 1,
  primitives: ['MATCH_RULE', 'EVAL_FORMULA', 'TRAVERSE_GRAPH', 'APPLY_DECISION_TREE', 'SCORE_KPI'],
  samplePlans: [
    {
      id: 'rp-low-stock',
      name: 'Low stock reasoning plan',
      steps: [
        { id: 'r1', primitive: 'MATCH_RULE', inputRefs: ['br-fifo'], outputRef: 'ruleHits', description: 'Match inventory rules' },
        { id: 'r2', primitive: 'EVAL_FORMULA', inputRefs: ['f-mrp-net'], outputRef: 'netNeed', description: 'Compute MRP net' },
        { id: 'r3', primitive: 'APPLY_DECISION_TREE', inputRefs: ['dec-low-stock'], outputRef: 'decisionPath', description: 'Walk low-stock decision' },
        { id: 'r4', primitive: 'TRAVERSE_GRAPH', inputRefs: ['c-warehouse'], outputRef: 'neighbors', description: 'Related concepts' },
      ],
    },
  ],
  llmEnabled: false,
  sideEffects: 'NONE',
}
