import {
  executeCompleteOperation,
  executeCompletionConfirmation,
  executeDeclareProduction,
  executeFinishWorkSession,
  executeMoveBundle,
  executePauseOperation,
  executePauseWorkSession,
  executeResumeOperation,
  executeResumeWorkSession,
  executeStartOperation,
  executeStartWorkSession,
} from './shop-floor-command.mapper'
import {
  mapBundleList,
  mapLaborTrackingList,
  mapMachineOptions,
  mapMachineStatusList,
  mapOperationProgressList,
  mapOperationsForOrder,
  mapOperatorOptions,
  mapSessionsForOrder,
  mapShopFloorContexts,
  mapShopFloorTimeline,
  mapWorkstationView,
} from './shop-floor.mapper'

export const shopFloorApplicationService = {
  query: {
    contexts: mapShopFloorContexts,
    operationsForOrder: mapOperationsForOrder,
    sessionsForOrder: mapSessionsForOrder,
    machineStatusList: mapMachineStatusList,
    laborTrackingList: mapLaborTrackingList,
    operationProgress: mapOperationProgressList,
    workstationView: mapWorkstationView,
    machineOptions: mapMachineOptions,
    operatorOptions: mapOperatorOptions,
    bundles: mapBundleList,
    timeline: mapShopFloorTimeline,
  },
  command: {
    declareProduction: executeDeclareProduction,
    completionConfirmation: executeCompletionConfirmation,
    startOperation: executeStartOperation,
    pauseOperation: executePauseOperation,
    resumeOperation: executeResumeOperation,
    completeOperation: executeCompleteOperation,
    moveBundle: executeMoveBundle,
    startWorkSession: executeStartWorkSession,
    pauseWorkSession: executePauseWorkSession,
    resumeWorkSession: executeResumeWorkSession,
    finishWorkSession: executeFinishWorkSession,
  },
}
