import {
  evaluateFormula,
  queryBusinessRules,
  queryConceptNeighbors,
  queryDecisions,
  queryDictionary,
  queryFlowByCode,
  queryFormulae,
  queryMachines,
  queryManufacturingKnowledgeCoverage,
  queryManufacturingKnowledgeGraph,
  queryManufacturingKnowledgeSnapshot,
  queryOperations,
  queryProductionFlows,
  queryKpis,
} from '@/domain/brain/manufacturing-knowledge'

export const brainKnowledgeApplicationService = {
  query: {
    snapshot: queryManufacturingKnowledgeSnapshot,
    coverage: queryManufacturingKnowledgeCoverage,
    graph: queryManufacturingKnowledgeGraph,
    neighbors: queryConceptNeighbors,
    formulae: queryFormulae,
    evaluateFormula,
    rules: queryBusinessRules,
    dictionary: queryDictionary,
    flows: queryProductionFlows,
    flow: queryFlowByCode,
    decisions: queryDecisions,
    machines: queryMachines,
    operations: queryOperations,
    kpis: queryKpis,
  },
}
