import {
  mapCapacityLines,
  mapCapacityMachines,
  mapCapacityOperators,
  mapCapacityWorkshops,
  mapDailyProductionEntries,
  mapLinePlans,
  mapOperationTracking,
  mapProductionCalendar,
  mapProductionDashboard,
  mapProductionOrderById,
  mapProductionOrders,
  mapProductionSchedule,
  mapProductionTimeline,
  mapWorkshopPlans,
} from './production-planning.mapper'

export const productionPlanningApplicationService = {
  getDashboard: mapProductionDashboard,
  getCalendar: mapProductionCalendar,
  getOrders: mapProductionOrders,
  getOrderById: mapProductionOrderById,
  getSchedule: mapProductionSchedule,
  getCapacityWorkshops: mapCapacityWorkshops,
  getCapacityLines: mapCapacityLines,
  getCapacityMachines: mapCapacityMachines,
  getCapacityOperators: mapCapacityOperators,
  getWorkshopPlans: mapWorkshopPlans,
  getLinePlans: mapLinePlans,
  getDailyEntries: mapDailyProductionEntries,
  getOperationTracking: mapOperationTracking,
  getTimeline: mapProductionTimeline,
}
