import { mapBarcodeDashboard } from './barcode-mobile.mapper'
import {
  executeFgReceiptScan,
  executeFlushOfflineQueue,
  executeMaterialIssueScan,
  executeProductionScan,
  executeReceivingScan,
  executeScanBundle,
  executeScanFinishedGoods,
  executeScanMaterial,
  executeScanOperation,
  executeScanProduction,
  executeShipmentScan,
  executeSyncOfflineQueue,
  executeWorkflowScan,
  queryBundleLabel,
  queryFinishedGoodsLabel,
  queryOfflineQueue,
  queryPalletLabel,
} from './barcode-mobile-command.mapper'

export const barcodeMobileApplicationService = {
  query: {
    dashboard: mapBarcodeDashboard,
    offlineQueue: queryOfflineQueue,
    bundleLabel: queryBundleLabel,
    palletLabel: queryPalletLabel,
    finishedGoodsLabel: queryFinishedGoodsLabel,
  },
  command: {
    executeScanOperation,
    executeScanBundle,
    executeScanMaterial,
    executeScanFinishedGoods,
    executeScanProduction,
    executeWorkflowScan,
    executeReceivingScan,
    executeMaterialIssueScan,
    executeProductionScan,
    executeFgReceiptScan,
    executeShipmentScan,
    syncOfflineQueue: executeSyncOfflineQueue,
    flushOfflineQueue: executeFlushOfflineQueue,
  },
}
