/**
 * Persistence ports — public barrel export.
 * @see docs/architecture/PERSISTENCE-CONSTITUTION.md
 */

export * from './persistence.types'
export * from './persistence-aggregates'
export * from './repository.base'

export * from './aggregates/sales-order.repository'
export * from './aggregates/product-card.repository'
export * from './aggregates/production-order.repository'
export * from './aggregates/execution-context.repository'
export * from './aggregates/bundle.repository'
export * from './aggregates/split-execution.repository'
export * from './aggregates/stock-ledger.repository'
export * from './aggregates/stock-card.repository'
export * from './aggregates/approval-workflow.repository'
export * from './aggregates/entity-revision.repository'
export * from './aggregates/purchase-order.repository'
export * from './aggregates/fabric-card.repository'
export * from './aggregates/accessory-card.repository'
export * from './aggregates/warehouse.repository'
export * from './aggregates/workshop.repository'
export * from './aggregates/production-line.repository'
export * from './aggregates/customer.repository'
export * from './aggregates/brain-config.repository'
export * from './aggregates/master-data-approval.repository'

export * from './lookups/master-data-lookup.repository'
export * from './lookups/master-data-lookup-registry.port'
export * from './lookups/master-data-enterprise-config.port'

export * from './streams/production-daily-entry-stream.repository'
export * from './streams/production-order-snapshot-stream.repository'
export * from './streams/operation-daily-entry-stream.repository'
export * from './streams/operation-work-session-stream.repository'
export * from './streams/quality-gate-evaluation-stream.repository'
export * from './streams/wip-transfer-stream.repository'
export * from './streams/execution-event-stream.repository'
export * from './streams/stock-movement-stream.repository'
export * from './streams/audit-log-stream.repository'
export * from './streams/order-timeline-stream.repository'
export * from './streams/brain-decision-memory-stream.repository'
export * from './streams/master-data-change-stream.repository'
export * from './streams/master-data-brain-change-stream.repository'

export * from './outbox/domain-event-outbox.repository'
export * from './read-models/wip-position.read-model'
export * from './read-models/production-calendar.read-model'
export * from './collections/collection-repository.base'
export * from './collections/attachment-collection.repository'
export * from './collections/comment-collection.repository'
export * from './collections/entity-tag-collection.repository'
export * from './collections/watcher-collection.repository'
export * from './collections/ai-memory-collection.repository'
export * from './collections/human-feedback-collection.repository'
export * from './collections/enterprise-timeline-collection.repository'
export * from './unit-of-work.port'
export * from './persistence-registry'
